#!/usr/bin/env sh

COMMIT_MSG_FILE=$1

### util

# STDIN
escapeNewlines() {
    { cat; printf x; } |
        tr -d '\r' |
        sed 's|\([<>]\)|<\1>|g; s|^|<LF>|g' |
        tr -d '\n' |
        sed 's|^<LF>||g; s|x$||g'
}

# STDIN
unescapeNewlines() {
    sed 's|<LF>|\n|g; s|<\([<>]\)>|\1|g'
}

# $1=STRING
isSingleLine() {
    [ "${1}" = "$(printf %s "${1}" | tr -d '\n\r')" ]
}

# $1=REGEX $2=STRING
match() {
    printf %s "${2}" | grep -- "${1}" >/dev/null
}

# $1..n=ARGS
exitError() {
    printf '!!! ERROR'
    i=0
    while i=$((i + 1)); [ ${i} -le $# ]; do
        eval "printf ': %s' \"\${${i}}\""
    done
    printf ' !!!\n'
    exit 1
}

### FOOTER

footers=''
FOOTER() {
    if [ $# -lt 2 ]; then
        exitError FOOTER 'invalid number of arguments' $#
    fi
    if ! isSingleLine "${1}" || ! match "^[^$(printf ' \t')]\\+$" "${1}"; then
        exitError FOOTER 'invalid footer name' "${1}"
    fi
    if [ ! "${footers}" = '' ]; then
        footers="${footers}<LF>"
    fi
    if isSingleLine "${2}"; then
        footers="${footers}$(printf %s "${1}" | escapeNewlines): $(printf %s "${2}" | escapeNewlines)"
    else
        footers="${footers}$(printf %s "${1}" | escapeNewlines):<LF>$(printf %s "${2}" | escapeNewlines | sed 's|^\(<LF>\)*||g; s|\(<LF>\)*$||g')"
    fi
}

### USE_MESSAGE

useMessage=''
USE_MESSAGE() {
    useMessage=1
}

### main

. "${COMMIT_MSG_FILE}"

if [ ${useMessage} ]; then
    printf %s "${MESSAGE}" >"${COMMIT_MSG_FILE}"
    exit 0
fi

if [ "${TYPE}" = '' ] || ! isSingleLine "${TYPE}"; then
    exitError TYPE 'invalid format' "${TYPE}"
fi
printf %s "${TYPE}" >"${COMMIT_MSG_FILE}"

if [ ! "${SCOPE}" = '' ]; then
    if ! isSingleLine "${SCOPE}"; then
        exitError SCOPE 'invalid format' "${SCOPE}"
    fi
    printf '(%s)' "${SCOPE}" >>"${COMMIT_MSG_FILE}"
fi

if [ "${DESCRIPTION}" = '' ] || ! isSingleLine "${DESCRIPTION}"; then
    exitError DESCRIPTION 'invalid format' "${DESCRIPTION}"
fi
printf ': %s\n\n' "${DESCRIPTION}" >>"${COMMIT_MSG_FILE}"

printf '%s\n\n' "${BODY}" >>"${COMMIT_MSG_FILE}"

printf %s "${footers}" | unescapeNewlines >>"${COMMIT_MSG_FILE}"
