#!/usr/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

commitMsgDefault="$(cat "${COMMIT_MSG_FILE}")"

printf '#!/usr/bin/env sh\n\n' >"${COMMIT_MSG_FILE}"

eotNonce="____________EOT$(date +%s)"

cat <<EOT >>"${COMMIT_MSG_FILE}"
TYPE #change #rm #revert #feat #docs
SCOPE #scope_name(optional)
DESCRIPTION #description

BODY <<${eotNonce}
${eotNonce}

# FOOTER footer_name footer_value
FOOTER files <<${eotNonce}
$(git status --porcelain --verbose --untracked-files=no | grep '^[A-Z]' | sed 's|^\([A-Z]\)[A-Z]*\s*\([^ ]\)|\1 \2|g')
${eotNonce}
$(
    gitBranch="$(git rev-parse --abbrev-ref HEAD)"
    if printf %s "${gitBranch}" | grep '^[A-Z]\+-[0-9]\+' >/dev/null; then
        printf '%s\n' "FOOTER jira-ticket ${gitBranch}"
    fi
)

### Default/Old message
#
# MESSAGE <<${eotNonce}
cat <<${eotNonce} >/dev/null
${commitMsgDefault}
${eotNonce}
EOT

exit 0
