#!/usr/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

commitMsgDefault="$(cat "${COMMIT_MSG_FILE}")"

printf '#!/usr/bin/env sh\n\n' >"${COMMIT_MSG_FILE}"

eotNonce="____________EOT$(date +%s)"

cat <<EOT >>"${COMMIT_MSG_FILE}"
TYPE=''
SCOPE=''
DESCRIPTION=''

BODY="
"

# FOOTER footer_name footer_value
FOOTER files '
$(git status --porcelain --verbose --untracked-files=no | grep '^[A-Z]' | sed 's|^\([A-Z]\)[A-Z]*\s*\([^ ]\)|\1 \2|g')
'
$(
    gitBranch="$(git rev-parse --abbrev-ref HEAD)"
    if printf %s "${gitBranch}" | grep '^[A-Z]\+-[0-9]\+' >/dev/null; then
        printf '%s\n' "FOOTER jira-ticket ${gitBranch}"
    fi
)

### OLD MESSAGE

# USE_MESSAGE
MESSAGE='
${commitMsgDefault}
'
EOT

exit 0
